language: go
go:
  - 1.x
before_install:
  - go get github.com/mattn/goveralls
script:
  - ./githooks/pre-commit
  - go test -cpu=1 -v -covermode=count -coverprofile=coverage.out ./...
  - go test -race -v ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
